namespace SharpPDF.Lib
{
    public enum PdfExceptionCodes
    {
        FILE_ABRUPTLY_TERMINATED,
        EXPECTED_DELIMITER,
        INVALID_NAMEOBJECT_TOKEN,
        UNKNOWN_TOKEN, 
        INVALID_NUMBER_TOKEN,
        INVALID_INDIRECTOBJECT_TOKEN,
        INVALID_GENERATION,
        HEADER_NOT_FOUND,
        HEADER_INCORRECT_VERSION,
        BOF,
        INVALID_EOF,
        INVALID_XREF,
        DICTIONARY_KEY_NAMEOBJECT,
        INVALID_ARRAY,
        INVALID_DICTIONARY,
        DICTIONARY_VALUE_LENGTH_INTEGER,
        INVALID_DICTIONARY_STREAM,
        INVALID_STREAM,
        INVALID_NUMBER,
        INDIRECT_REFERENCE_MISSING,
        INVALID_TRAILER,
        INVALID_CONTENT,
    }  
}